### ISSUE TITLE
Encountering error when trying to reuse Remix ProductCard component

### ISSUE THREAD

**Issue by amyous** [Nosto/shopify-hydrogen#19]
Hi Nosto Team,

I have refactored my ProductCard component to be able to work with Storefront API data and the Nosto product data. However, I am encountering this error on the frontend:
```
Error: You must render this element inside a <Remix> element
```

I have narrowed down the issue to be with incompatibility with these Remix components and hooks:
```
import {Link, useFetcher, useMatches} from '@remix-run/react';
```

Would you be able to provide some context on why this might be the case and if Remix elements will be supported in the future?

Another question I have - is local development support on the roadmap?

Thanks!

**Comment by amyous** [comment]
Hi @sid2364,

I believe the Nosto product cards is this [component](https://github.com/Nosto/shopify-hydrogen-demo/blob/2a3f566fae36602e4c0b321e9b873faf74a8891d/app/components/nosto/NostoItem.jsx). As a workaround, we have created a separate ProductCard for the Nosto placements. Still, we would ideally like to reuse the same component across the site for consistency and user experience. The incompatibility with Remix means the quick add to cart can't be ajax.

**Comment by sid2364** [comment]
I think I see what you mean! Sorry for the confusion earlier. 

Assuming you are using client-side rendering for recommendations, the logic is implemented in our base package `nosto-react` [here](https://github.com/Nosto/nosto-react/blob/master/src/components/Provider/index.client.tsx#L82-L88). Remix is currently not supported there as `nosto-react` is Shopify agnostic. The solution you have in place might be a good way to go for now, unfortunately. I will also check with the team and brainstorm alternatives for your case.

**Comment by sid2364** [comment]
For your local development question, I believe Shopify's Oxygen deployment makes testing much simpler. What is your workflow currently?

**Comment by amyous** [comment]
To test Nosto placements, we have to trigger a deployment to an Oxygen preview environment, since the URL needs to be whitelisted from Nosto admin. However, this can be a bit tedious and slow when you're trying to debug things and while you're still trying to figure out how things work. But all good now, we have what we need working, thanks!

**Comment by sid2364** [comment]
What I usually do while trying to test Nosto locally is use a tool like ngrok and serve to a temporary host like xxxxxxx.ngrok.app instead of localhost. This can then be added to the whitelisted hosts in the Nosto admin. 

For Oxygen deployments, this wouldn't work unfortunately, as it generates a new URL every commit. :(
